### ISSUE TITLE
tabar设置文字颜色没起作用

### ISSUE THREAD

**Issue by wangyifei6817** [Damonvvong/DWCustomTabBarDemo#1]
[[UITabBar appearance]setTintColor:[UIColor redColor]];
貌似apple现在推荐用这种方式去设置选中颜色了吧

原工程里那种并没有起作用

**Comment by Damonvvong** [comment]
@wangyifei6817 UITabBar 里面的文字选中颜色是有状态的。你可以参考一下< DWTabBarController.m >的 66 行 的setUpTabBarItemTextAttributes 对选中文字颜色进行设置。按钮的颜色也要根据颜色来设置。
