### ISSUE TITLE
push到下一个页面

### ISSUE THREAD

**Issue by xinqidian** [Damonvvong/DWCustomTabBarDemo#2]
怎么隐藏底部tabBar

**Comment by loarland** [comment]
作者的tabbarController和tabbar都是继承系统的控件，你就按照系统控件本来的隐藏方式就行啦
hidesBottomBarWhenPushed

**Comment by Damonvvong** [comment]
@loarland 感谢回答。希望大家提问题之前可以先谷歌一下
